version: '3'
services:
  db:
    image: mysql:5.7.21
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
  rails:
    build: .
    command: bundle exec pumactl start
    ports:
      - "3001:3001"
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: webpacker:3035
    env_file:
      - .env
    depends_on:
      - db
      - webpacker
  webpacker:
    build: .
    command: bin/webpack-dev-server
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    ports:
      - '3035:3035'
