defaults: &defaults
  working_directory: ~/emojix
  docker:
    - image: circleci/ruby:2.4.2-node
      environment:
        RAILS_ENV: test

    - image: circleci/mysql:5.7 

version: 2
jobs:
  bundle_dependencies:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/emojix
      - restore_cache:
          keys:
            - v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/emojix/vendor/bundle
      - persist_to_workspace:
          root: ~/emojix
          paths: vendor/bundle

  rspec_test:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/emojix
      - run: cp config/database.yml.ci config/database.yml
      - run: bundle --path vendor/bundle
      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load
      - run: bundle exec rspec

workflows:
  version: 2
  build_and_test:
    jobs:
      - bundle_dependencies
      - rspec_test:
          requires:
            - bundle_dependencies
